added input to automate versioning release

diff --git a/.github/workflows/jekyll-docker.yml b/.github/workflows/jekyll-docker.yml
--- a/.github/workflows/jekyll-docker.yml
+++ b/.github/workflows/jekyll-docker.yml
@@ -22,10 +22,20 @@ on:
         options:
         - false
         - true
+      ReleaseType:
+        type: choice
+        description: 'Type of Release'
+        required: true
+        options:
+        - MAJOR
+        - MINOR
+        - PATCH
       Release:
         description: 'Select the release name'
         required: false
         default: 'latest'
+
+
 
 permissions:
   id-token: write
@@ -254,12 +264,10 @@ jobs:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
         tag=${{ env.RC }}
-
-        gitTag=`git tag -l | sort -V | grep ${{ env.SERVICE }}-$tag | tail -n 1`
-        echo "Latest git tag"
-        echo $gitTag
+        releaseType=${{ inputs.ReleaseType }}
 
         # Determine semantic version components
+        gitTag=`git tag -l | sort -V | grep ${{ env.SERVICE }}-$tag | tail -n 1`
         if [ x"$gitTag" == x ]; then
           MAJOR=1
           MINOR=0
@@ -271,8 +279,25 @@ jobs:
           PATCH=${versionComponents[2]}
         fi
 
-        # Increase version components
-        PATCH=$((PATCH+1))
+        # Increment version components based on ReleaseType
+        case $releaseType in
+          MAJOR)
+            MAJOR=$((MAJOR+1))
+            MINOR=0
+            PATCH=0
+            ;;
+          MINOR)
+            MINOR=$((MINOR+1))
+            PATCH=0
+            ;;
+          PATCH)
+            PATCH=$((PATCH+1))
+            ;;
+          *)
+            echo "Invalid ReleaseType provided. Please choose MAJOR, MINOR, or PATCH."
+            exit 1
+            ;;
+        esac
 
         # Create semantic version tag
         NEW_TAG=${MAJOR}.${MINOR}.${PATCH}
@@ -286,7 +311,7 @@ jobs:
         git tag $NEW_TAG
         git push origin $NEW_TAG
 
-        # Create GitHub release
+        # Create GitHub release with incremented version
         gh release create $NEW_TAG -t "$NEW_TAG" -n "Release $NEW_TAG"
 
         echo "GitHub release created for tag: $NEW_TAG"
