fix conditions

diff --git a/.github/workflows/jekyll-docker.yml b/.github/workflows/jekyll-docker.yml
--- a/.github/workflows/jekyll-docker.yml
+++ b/.github/workflows/jekyll-docker.yml
@@ -63,10 +63,16 @@ jobs:
       id: determine-version
       run: |
         git fetch --tags
-        latestTag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
+        latestTag=$(git describe --tags --abbrev=0 2>/dev/null)
         currentVersion=${latestTag}
-        
-        echo "CURRENT_VERSION=$currentVersion" >> $GITHUB_ENV
+
+        # Check if the current version follows the semantic versioning format
+        if ! [[ $currentVersion =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+          echo "Invalid semantic version format. Starting from v0.1.0"
+          currentVersion="v0.0.0"
+        else
+          echo "CURRENT_VERSION=$currentVersion" >> $GITHUB_ENV
+        fi
 
     - name: Increment version
       id: increment-version
