versioning now on inputs based

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -63,10 +63,26 @@ jobs:
         run: |
           echo "LATEST_TAG=${{ steps.fetch-tag.outputs.LATEST_TAG }}" >> $GITHUB_ENV
           currentVersion=${{ env.LATEST_TAG }}
-          newVersion=$(semver --increment ${{ github.event_name }} --from $currentVersion)
+          releaseType=${{ github.event.inputs.ReleaseType }}
+          
+          case $releaseType in
+            MAJOR)
+              newVersion=$(semver --increment major $currentVersion)
+              ;;
+            MINOR)
+              newVersion=$(semver --increment minor $currentVersion)
+              ;;
+            PATCH)
+              newVersion=$(semver --increment patch $currentVersion)
+              ;;
+            *)
+              echo "Invalid ReleaseType provided."
+              exit 1
+              ;;
+          esac
+
           echo "New version: $newVersion"
           echo "NEW_VERSION=$newVersion" >> $GITHUB_ENV
-
 
       # - name: Determine new version
       #   id: determine-version
